/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.RestaDatos;
import io.swagger.model.SumaDatos;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-07-26T07:54:49.951Z")

@Api(value = "operacion", description = "the operacion API")
public interface OperacionApi {

    @ApiOperation(value = "Realiza la resta de posible ampliacion", nickname = "restarEnteros", notes = "", response = Long.class, tags={ "Lista de sumandos", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Resultado operacion suma", response = Long.class) })
    @RequestMapping(value = "/operacion/resta",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Long> restarEnteros(@ApiParam(value = "" ,required=true )  @Valid @RequestBody RestaDatos listaSumandos);


    @ApiOperation(value = "Realiza la suma de dos sumandos", nickname = "sumarEnteros", notes = "", response = Long.class, tags={ "Lista de sumandos", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Resultado operacion suma", response = Long.class) })
    @RequestMapping(value = "/operacion/suma",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Long> sumarEnteros(@ApiParam(value = "" ,required=true )  @Valid @RequestBody SumaDatos listaSumandos);

}
