/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.RestaDatos;
import io.swagger.model.SumaDatos;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-07-26T07:54:49.951Z")

@Api(value = "operacion", description = "the operacion API")
public interface OperacionApi {

    @ApiOperation(value = "Realiza la resta de numeros enteros", nickname = "restarEnteros", notes = "", response = Long.class, tags={ "Operador enteros", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Resultado operacion resta", response = Long.class) })
    @RequestMapping(value = "/operacion/resta",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Long> restarEnteros(@ApiParam(value = "" ,required=true )  @Valid @RequestBody RestaDatos restaDatos);


    @ApiOperation(value = "Realiza la suma de dos sumandos", nickname = "sumarEnteros", notes = "", response = Long.class, tags={ "Operador enteros", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Resultado operacion suma", response = Long.class) })
    @RequestMapping(value = "/operacion/suma",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Long> sumarEnteros(@ApiParam(value = "" ,required=true )  @Valid @RequestBody SumaDatos sumaDatos);

}
